### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jillesme** [jordanrobert/React-Redux-Snake#3]
Hey man, I saw your reddit post and thought to review your code. It looks really good.

In [utils/index.js](https://github.com/jordanrobert/React-Redux-Snake/blob/master/src/utils/index.js#L3) you use a `.map` to set a boolean. As you don't care about the result of map you're better off using `.forEach`. Map only makes sense if you care about the result. (e.g. `const doubled = [1, 2, 3].map(d => d * 2);`). I feel like you could also use `return arrCoords.some((coord) => coords[0] === matchCoords[0] && coords[1] === matchCoords[1])`. 

Next up [actions/index.js](https://github.com/jordanrobert/React-Redux-Snake/blob/master/src/actions/index.js#L1). It's really nice. Maybe you could improve the moveSnake function a bit by using `const` for the variables you don't redeclare (direction, headCoords, newHead). I'm a big fan of object maps, so you could rewrite [this](https://github.com/jordanrobert/React-Redux-Snake/blob/master/src/actions/index.js#L5-L11) function to:

``` js
const headMap = {
  DOWN: [headCoords[0], headCoords[1]+1],
  UP: [headCoords[0], headCoords[1]-1],
  LEFT: [headCoords[0]-1, headCoords[1]],
  RIGHT: [headCoords[0]+1, headCoords[1]]
};
coords.push(headMap[direction]);
```

Moving on the the [Snake component](https://github.com/jordanrobert/React-Redux-Snake/blob/master/src/components/Snake.js#L13). Again, super nice. I do think the ...lostStyling is a little overkill. What about:

``` js
let style = {
  left: coords[0] * SQUARE_SIZE + 'px',
  top: coords[1] * SQUARE_SIZE + 'px',
  background: props.lost ? 'red' : ''
}
```

Finally there's the Game.js container. In the constructor `this.snakeInterval;` doesn't do anything as you're not assigning it to a value. Also, try to make use of ES6's Object Destructuring! I see a ton of `this.props.snake, this.props.game`. Just simply add `const { snake, game } = this.props;` to your functions that use those and get rid of all those `this.props`. It's additional typing you don't need!

That's really all I could think of. It's really well coded! The only thing I really dislike is the use of tabs (instead of the current "JavaScript standard": 2 spaces). But that's generally a personal preference. 

Well done man!

**Comment by jordanrobert** [comment]
Hey, sorry for the late reply. I like all those suggestions, and I'm going to make the changes when I get some free time. Thanks a ton, man!

Also, only reason I did the ...lostStyling overkill was because I was originally going to have more style changes than just background, but I decided against it and never cleaned it up :).
